services:
  backend:
    build:
      context: rnaseq-app/backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - API_PORT=5050         # ‚Üê was PORT
      - STORAGE_ROOT=/data/storage
      - QC_ROOT=/data/qc
    volumes:
      - storage:/data/storage
      - qc:/data/qc

  frontend:
    build:
      context: rnaseq-app/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  storage:
  qc:
